version: "3.9"
services:
  postgres:
    container_name: postgres_rating_system
    image: postgres:latest
    environment:
      POSTGRES_DB: "RatingDbContext"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
volumes: 
  postgres-data: